version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app
    environment:
      - MODEL_PATH=/app/models/Llama-3.2-3B-Instruct-Q8_0.gguf
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
